name: Check Pods and Create Folder
on:
  push:
    branches: [master]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Execute remote commands
      id: remote-commands
      uses: appleboy/ssh-action@v1.2.2
      with:
        proxy_host: ${{ secrets.BASTION_IP }}
        proxy_port: ${{ secrets.BASTION_PORT }}
        proxy_username: ${{ secrets.BASTION_USER }}
        proxy_password: ${{ secrets.BASTION_PASS }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          # Создание папки qwe в корне
          sudo mkdir -p /qwe
          sudo chmod 755 /qwe
          echo "Папка /qwe создана"
          ls -ld /qwe
