name: Run Python Script
on:
  push:
    branches: [ "master" ]
jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute Python script
        run: python Hello.py
